#! /bin/bash

# g++ -o next_km.run -mavx512f -mavx512f -mavx512cd -mavx512er -mavx512pf -mavx512vl -mavx512dq -mavx512bw -fopenmp final_mbkm_simd_thread_10e.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
# g++ -o next_km.run next_km.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
# g++ -o next_mbkm.run next_mbkm.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
# g++ -o next_srmbkm.run next_srmbkm.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
# g++ -o next_total.run next_total.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
# g++ -o next_total_pt.run -pthread next_total_pt.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
# g++ -o next_total_pt_sd.run -pthread -mavx512f -mavx512f -mavx512cd -mavx512er -mavx512pf -mavx512vl -mavx512dq -mavx512bw next_total_pt_sd.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
# g++ -o next_total_pt_sd_loss.run -pthread -mavx512f -mavx512f -mavx512cd -mavx512er -mavx512pf -mavx512vl -mavx512dq -mavx512bw next_total_pt_sd_loss.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
# g++ -o next_total_ptsd_clear.run -pthread -mavx512f -mavx512f -mavx512cd -mavx512er -mavx512pf -mavx512vl -mavx512dq -mavx512bw next_total_ptsd_clear.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
# g++ -o next_srnnn.run -pthread -mavx512f -mavx512f -mavx512cd -mavx512er -mavx512pf -mavx512vl -mavx512dq -mavx512bw next_srnnn.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
# g++ -o next_srnnn_float2.run -pthread -mavx512f -mavx512f -mavx512cd -mavx512er -mavx512pf -mavx512vl -mavx512dq -mavx512bw next_srnnn_float.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
# g++ -o next_srnnn_float_pt.run -pthread -mavx512f -mavx512f -mavx512cd -mavx512er -mavx512pf -mavx512vl -mavx512dq -mavx512bw next_srnnn_float_pt.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
# g++ -o next_srnnn_pt_ld.run -pthread -mavx512f -mavx512f -mavx512cd -mavx512er -mavx512pf -mavx512vl -mavx512dq -mavx512bw next_srnnn_pt_ld.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
# g++ -o next_srnnn_float_pt_sd.run -pthread -mavx512f -mavx512f -mavx512cd -mavx512er -mavx512pf -mavx512vl -mavx512dq -mavx512bw next_srnnn_float_pt_sd.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3

g++ -o next_test.run -pthread -mavx512f -mavx512f -mavx512cd -mavx512er -mavx512pf -mavx512vl -mavx512dq -mavx512bw next_test.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
g++ -o next_test_srnnn.run -pthread -mavx512f -mavx512f -mavx512cd -mavx512er -mavx512pf -mavx512vl -mavx512dq -mavx512bw next_test_srnnn.cpp ../util/timer.cpp ../util/dataIo.cpp ../util/arguments.cpp ../util/allocation.cpp ../mckm/mckm.cpp ../cmdparser/cmdlineparser.cpp ../cmdparser/cmdlineparser.h ../logger/logger.h ../logger/logger.cpp -O3
